export const ADD_POST = 'ADD_POST';
export const UPDATE_POST_MESSAGE = 'UPDATE_POST_MESSAGE';
export const ADD_DIALOG_MESSAGE = 'ADD_DIALOG_MESSAGE';
export const UPDATE_DIALOG_MESSAGE = 'UPDATE_DIALOG_MESSAGE';